from pygame.math import Vector2 as vec
SPACE = 50
TILESIZE = 32
ROWS = 20
COLS = 20

SCREENWIDTH = ROWS * TILESIZE
SCREENHEIGHT = COLS * TILESIZE

LEVEL_WIDTH = SCREENWIDTH - SPACE
LEVEL_HEIGHT = SCREENHEIGHT - SPACE

PACMAN_STARTPOS = vec(0, 0)

ROWS = 30
COLS = 28

### COLORS ###
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
